# Generated by Django 5.2.1 on 2025-05-22 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_bid_placed_at_listing_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
