# Generated by Django 5.2.1 on 2025-07-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_certificate_course_duration_course_enrolled_and_more'),
        ('users', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='courses.course'),
        ),
    ]
